// SPDX-License-Identifier: GPL-3.0-or-later

using LinFan.Core.Models;

namespace LinFan.Core.Services;

/// <summary>
/// Leitet aus den Einbau-Positionen der Lüfter (<see cref="FanConfig.Location"/>) einen Airflow-Vorschlag
/// ab: eine grobe Gehäuse-Druckbilanz und rollenbasierte Default-Kurven + Zuordnungen. Reine,
/// seiteneffektfreie Funktion über eine <see cref="AppConfig"/> - kein Hardware-/IPC-/UI-Zugriff
/// (Muster wie <see cref="ProfileService"/> / <see cref="DefaultProfiles"/>). Die GUI rechnet damit lokal
/// einen Vorschlag, zeigt ihn an und schreibt ihn bei „Übernehmen" über den normalen Speicherpfad zurück.
/// </summary>
/// <remarks>
/// <para><b>Ausgeblendete Kanäle bleiben außen vor.</b> Lüfter/Sensoren mit <c>Hidden</c> sind für den
/// Nutzer „nicht vorhanden" (typisch: ein totes PWM-/Temp-Interface ohne Werte) - sie bekommen keinen
/// Vorschlag, zählen nicht in die Druckbilanz und taugen nicht als Kurvenquelle.</para>
/// <para><b>Sensor-Zuordnung ist eine Namens-/Gruppen-Heuristik.</b> <see cref="SensorConfig"/> trägt
/// keine Art (CPU/GPU/Temp): diese Information stammt aus der Hardware-Discovery, nicht aus der
/// persistierten Config. Quell-Sensoren werden daher über Schlüsselwörter in Name <i>und</i> Gruppe
/// geraten (AMD-SoC heißt z. B. „… 5800X SoC", hängt aber in der Gruppe „CPU"); schlägt das fehl, fällt
/// der Vorschlag auf den ersten verfügbaren Sensor zurück und setzt einen Hinweis. Komponenten-Kurven
/// (CPU/GPU) nehmen <i>alle</i> Treffer ihrer Komponente und mitteln sie (<see cref="SensorAggregation.Avg"/>):
/// Offset-Sensoren wie AMDs Tctl oder ein GPU-Hot-Spot liegen konstant deutlich über den übrigen Werten,
/// mit Max würde die Kurve nur diesen Offset abbilden.</para>
/// <para>Die Druckbilanz ist bewusst grob: ohne echte CFM-Werte dient die kalibrierte Max-RPM als Proxy,
/// und ohne Kalibrierung wird nur nach Anzahl gezählt.</para>
/// <para>Jede <see cref="FanLocation"/> ist in <c>Spec(...)</c> <b>an einer Stelle</b> auf Richtung und
/// Rolle abgebildet; die Kurvenvorlage hängt an der <see cref="AirflowRole"/> (compiler-geprüfter
/// <c>switch</c>). Neue Positionen brauchen daher nur einen Eintrag, nicht fünf verstreute Zweige.</para>
/// <para><b>Keine Anzeigetexte im Core:</b> Hinweise und Begründungen sind Codes
/// (<see cref="AirflowHint"/> / <see cref="AirflowReason"/>), die die GUI übersetzt; die Namen der
/// vorgeschlagenen Kurven sind neutral englisch und können über <c>curveNames</c> (Key = stabile
/// Kurven-Id) lokalisiert übergeben werden - sie werden persistiert (Muster wie <see cref="DefaultProfiles"/>).</para>
/// </remarks>
public static class AirflowTuneService
{
    /// <summary>Schwelle für „nennenswert" mehr Einlass/Auslass (Verhältnis), darunter gilt es als ausgeglichen.</summary>
    private const double BalanceThreshold = 1.15;

    // ── Öffentliche API ─────────────────────────────────────────────────────────

    /// <summary>Bildet eine <see cref="FanLocation"/> auf ihre Luftstrom-Richtung ab (für die Druckbilanz).</summary>
    public static AirflowDirection DirectionOf(FanLocation location) => Spec(location).Direction;

    /// <summary>
    /// True if the location maps to a specific airflow role (not None/Default) - i.e. the analysis can
    /// derive a role-based curve from it. Trigger for the airflow-driven onboarding profiles.
    /// </summary>
    public static bool HasRoleSpecificCurve(FanLocation location) =>
        Spec(location).Role is not (AirflowRole.None or AirflowRole.Default);

    /// <summary>Prefix every curve id generated here carries (<c>airflow-cpu</c> …).</summary>
    private const string CurveIdPrefix = "airflow-";

    /// <summary>
    /// True if the curve id was generated by this service. The ids are the only durable trace of a past
    /// analysis: they are stable, survive profile switches, and - unlike the display names - cannot be
    /// renamed away. A configuration therefore answers „was airflow tuning applied?" by itself, without a
    /// separate persisted flag.
    /// </summary>
    public static bool IsAirflowCurveId(string? curveId) =>
        curveId is not null && curveId.StartsWith(CurveIdPrefix, StringComparison.Ordinal);

    /// <summary>
    /// Analysiert die Lüfter-Positionen und liefert einen Vorschlag. Liest nur - schreibt nichts.
    /// </summary>
    /// <param name="config">Die zu analysierende Konfiguration.</param>
    /// <param name="curveNames">Optionale Anzeigenamen der vorgeschlagenen Kurven, Key = stabile
    /// Kurven-Id (<c>airflow-cpu</c> …) - die GUI reicht hier die lokalisierte Fassung durch, da die
    /// Namen persistiert werden. Ohne Eintrag gilt der neutrale englische Default.</param>
    public static AirflowTuneResult Analyze(AppConfig config, IReadOnlyDictionary<string, string>? curveNames = null)
        => Analyze(config, AirflowAggressiveness.Balanced, curveNames);

    /// <summary>
    /// Variant of <see cref="Analyze(AppConfig, IReadOnlyDictionary{string, string}?)"/> with an explicit
    /// aggressiveness: same roles, ids, and sensor sources - only the point tables differ. The default
    /// overload forwards with <see cref="AirflowAggressiveness.Balanced"/> (the pre-existing tables), so
    /// the settings' airflow section keeps its behavior.
    /// </summary>
    public static AirflowTuneResult Analyze(
        AppConfig config,
        AirflowAggressiveness aggressiveness,
        IReadOnlyDictionary<string, string>? curveNames = null)
    {
        ArgumentNullException.ThrowIfNull(config);

        // Ausgeblendete Kanäle sind für den Nutzer „nicht vorhanden" - komplett aus der Analyse halten.
        var visibleFans = config.Fans.Where(f => !f.Hidden).ToList();
        var visibleSensors = config.Sensors.Where(s => !s.Hidden).ToList();

        var hints = new List<AirflowHint>();
        SensorSources sensors = ResolveSensors(visibleSensors, hints);

        (PressureParts pressure, IReadOnlyList<AirflowHint> pressureHints) = ComputePressure(visibleFans);
        hints.AddRange(pressureHints);

        // Welche Rollen-Kurven werden tatsächlich gebraucht? (Netzteil → AirflowRole.None bekommt keine.)
        var usedRoles = new HashSet<AirflowRole>();
        foreach (FanConfig fan in visibleFans)
        {
            AirflowRole role = Spec(fan.Location).Role;
            if (role != AirflowRole.None)
                usedRoles.Add(role);
        }

        var curves = usedRoles
            .OrderBy(r => r)
            .Select(r => BuildCurve(r, aggressiveness, sensors, curveNames))
            .ToList();

        if (visibleSensors.Count == 0 && curves.Count > 0)
            hints.Add(AirflowHint.NoSensorsConfigured);

        var fanSuggestions = visibleFans.Select(BuildSuggestion).ToList();

        return new AirflowTuneResult
        {
            Pressure = pressure.Balance,
            IntakeWeight = pressure.Intake,
            ExhaustWeight = pressure.Exhaust,
            Hints = hints,
            SuggestedCurves = curves,
            Fans = fanSuggestions,
        };
    }

    /// <summary>
    /// Schränkt einen Vorschlag auf die übergebenen Lüfter ein (für die selektive Übernahme in der GUI -
    /// der Nutzer kreuzt einzelne Lüfter ab): behält nur deren Pro-Lüfter-Vorschläge und die davon
    /// referenzierten Kurven. Rein, ohne Seiteneffekte.
    /// </summary>
    public static AirflowTuneResult FilterToFans(AirflowTuneResult result, IEnumerable<string> fanIds)
    {
        ArgumentNullException.ThrowIfNull(result);
        ArgumentNullException.ThrowIfNull(fanIds);

        var keep = fanIds.ToHashSet(StringComparer.Ordinal);
        var fans = result.Fans.Where(f => keep.Contains(f.FanId)).ToList();
        var usedCurveIds = fans.Select(f => f.SuggestedCurveId).OfType<string>().ToHashSet(StringComparer.Ordinal);
        var curves = result.SuggestedCurves.Where(c => usedCurveIds.Contains(c.Id)).ToList();

        return result with { Fans = fans, SuggestedCurves = curves };
    }

    /// <summary>
    /// Übernimmt einen Vorschlag in eine neue <see cref="AppConfig"/>: fügt die vorgeschlagenen Kurven ein
    /// (ersetzt gleiche Ids) und setzt je Lüfter die <see cref="FanConfig.AssignedCurveId"/>. Ändert
    /// <b>nur</b> Kurven und Zuordnungen - Kalibrierung, PWM-Grenzen, Sichtbarkeit, Position und Gruppe
    /// bleiben unangetastet. Existiert ein aktives Profil, wird es mitgeführt (damit ein späteres
    /// <see cref="ProfileService.Apply"/> den Vorschlag nicht verwirft). Idempotent.
    /// </summary>
    public static AppConfig Apply(AppConfig config, AirflowTuneResult result)
    {
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(result);

        var assignMap = result.Fans.ToDictionary(s => s.FanId, s => s.SuggestedCurveId);

        var fans = config.Fans
            .Select(f => assignMap.TryGetValue(f.FanId, out string? curveId) ? f with { AssignedCurveId = curveId } : f)
            .ToList();

        IReadOnlyList<Profile> profiles = config.Profiles;
        if (config.ActiveProfileId is { } activeId && profiles.Any(p => p.Id == activeId))
        {
            profiles = profiles
                .Select(p => p.Id == activeId
                    ? p with
                    {
                        Curves = MergeCurves(p.Curves, result.SuggestedCurves),
                        Assignments = UpsertAssignments(p.Assignments, result.Fans),
                    }
                    : p)
                .ToList();
        }

        return config with
        {
            Curves = MergeCurves(config.Curves, result.SuggestedCurves),
            Fans = fans,
            Profiles = profiles,
        };
    }

    /// <summary>
    /// Builds the three onboarding profiles (silent/balanced/performance - ids and order match
    /// <see cref="DefaultProfiles.Build"/>) from the airflow analysis: each profile carries the role
    /// curves in the matching aggressiveness variant plus role-based assignments, restricted to
    /// <paramref name="assignableFanIds"/> (the controllable fans - read-only channels would only
    /// produce a failing SetPwm per tick). The analysis runs on the full config first, so the pressure
    /// balance still counts every visible fan. Curve ids are the stable <c>airflow-*</c> ids in all
    /// three profiles: only one profile is active at a time and <see cref="ProfileService.Apply"/>
    /// swaps the curve set wholesale, so assignments stay valid across profile switches. Fans whose
    /// role has no curve (PSU) get a <c>null</c> assignment - hardware auto, a regular state.
    /// </summary>
    /// <param name="curveNames">Localized curve names, key = stable curve id (persisted; see
    /// <see cref="Analyze(AppConfig, IReadOnlyDictionary{string, string}?)"/>).</param>
    public static IReadOnlyList<Profile> BuildProfiles(
        AppConfig config,
        IEnumerable<string> assignableFanIds,
        IReadOnlyDictionary<string, string>? curveNames = null,
        string silentName = "Silent",
        string balancedName = "Balanced",
        string performanceName = "Performance")
    {
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(assignableFanIds);

        var assignable = assignableFanIds.ToList();
        return new[]
        {
            BuildProfile("silent", silentName, AirflowAggressiveness.Silent, config, assignable, curveNames),
            BuildProfile("balanced", balancedName, AirflowAggressiveness.Balanced, config, assignable, curveNames),
            BuildProfile("performance", performanceName, AirflowAggressiveness.Performance, config, assignable, curveNames),
        };
    }

    private static Profile BuildProfile(
        string id,
        string name,
        AirflowAggressiveness aggressiveness,
        AppConfig config,
        IReadOnlyList<string> assignableFanIds,
        IReadOnlyDictionary<string, string>? curveNames)
    {
        AirflowTuneResult result = FilterToFans(Analyze(config, aggressiveness, curveNames), assignableFanIds);
        return new Profile
        {
            Id = id,
            Name = name,
            Curves = result.SuggestedCurves,
            Assignments = result.Fans.Select(f => new ProfileAssignment(f.FanId, f.SuggestedCurveId)).ToList(),
        };
    }

    // ── Position → (Richtung, Rolle, Klartext): die einzige Stelle pro Position ───

    /// <summary>Rolle eines Lüfters für die Kurvenwahl; <see cref="None"/> = bekommt keine Software-Kurve.</summary>
    private enum AirflowRole
    {
        None,
        Cpu,
        Gpu,
        Intake,
        Exhaust,
        Default,
    }

    /// <summary>Was eine <see cref="FanLocation"/> für den Tune bedeutet (Richtung + Rolle).</summary>
    private sealed record LocationSpec(AirflowDirection Direction, AirflowRole Role);

    /// <summary>
    /// Einzige Quelle pro Position: Richtung (für die Druckbilanz) und Rolle (für die Kurve).
    /// Der <c>_</c>-Zweig fängt nur undefinierte Enum-Werte ab (z. B. hand-editierte Config) → sichere Defaults.
    /// </summary>
    private static LocationSpec Spec(FanLocation location) => location switch
    {
        FanLocation.CpuCooler => new(AirflowDirection.Internal, AirflowRole.Cpu),
        FanLocation.Radiator => new(AirflowDirection.Internal, AirflowRole.Cpu),
        FanLocation.GpuCooler => new(AirflowDirection.Internal, AirflowRole.Gpu),
        FanLocation.CaseFrontIntake => new(AirflowDirection.Intake, AirflowRole.Intake),
        FanLocation.CaseBottomIntake => new(AirflowDirection.Intake, AirflowRole.Intake),
        FanLocation.CaseSideIntake => new(AirflowDirection.Intake, AirflowRole.Intake),
        FanLocation.CaseTopIntake => new(AirflowDirection.Intake, AirflowRole.Intake),
        FanLocation.CaseRearIntake => new(AirflowDirection.Intake, AirflowRole.Intake),
        FanLocation.CaseRearExhaust => new(AirflowDirection.Exhaust, AirflowRole.Exhaust),
        FanLocation.CaseTopExhaust => new(AirflowDirection.Exhaust, AirflowRole.Exhaust),
        FanLocation.CaseFrontExhaust => new(AirflowDirection.Exhaust, AirflowRole.Exhaust),
        FanLocation.CaseBottomExhaust => new(AirflowDirection.Exhaust, AirflowRole.Exhaust),
        FanLocation.CaseSideExhaust => new(AirflowDirection.Exhaust, AirflowRole.Exhaust),
        FanLocation.Psu => new(AirflowDirection.Internal, AirflowRole.None),
        FanLocation.Unspecified => new(AirflowDirection.Unknown, AirflowRole.Default),
        FanLocation.Other => new(AirflowDirection.Unknown, AirflowRole.Default),
        _ => new(AirflowDirection.Unknown, AirflowRole.Default),
    };

    // ── Druckbilanz ─────────────────────────────────────────────────────────────

    /// <summary>Zwischenergebnis der Druckbilanz (innerhalb des Service).</summary>
    private readonly record struct PressureParts(PressureBalance Balance, double Intake, double Exhaust);

    private static (PressureParts, IReadOnlyList<AirflowHint>) ComputePressure(IReadOnlyList<FanConfig> fans)
    {
        var hints = new List<AirflowHint>();

        var caseFans = fans
            .Select(f => (Fan: f, Dir: DirectionOf(f.Location)))
            .Where(x => x.Dir is AirflowDirection.Intake or AirflowDirection.Exhaust)
            .ToList();

        if (caseFans.Count == 0)
        {
            hints.Add(AirflowHint.NoCaseFans);
            return (new PressureParts(PressureBalance.Unknown, 0, 0), hints);
        }

        // Gewicht = kalibrierte Max-RPM (grober CFM-Proxy), sonst Anzahl. Nur einheitlich anwenden:
        // sobald ein Gehäuselüfter unkalibriert ist, zählen wir alle nach Anzahl (1), um Einheiten nicht zu mischen.
        bool allCalibrated = caseFans.All(x => x.Fan.Calibration is { MaxRpm: > 0 });
        if (!allCalibrated)
            hints.Add(AirflowHint.CountEstimateOnly);

        double Weight((FanConfig Fan, AirflowDirection Dir) x) =>
            allCalibrated ? x.Fan.Calibration!.MaxRpm : 1.0;

        double intake = caseFans.Where(x => x.Dir == AirflowDirection.Intake).Sum(Weight);
        double exhaust = caseFans.Where(x => x.Dir == AirflowDirection.Exhaust).Sum(Weight);

        if (intake <= 0)
            hints.Add(AirflowHint.NoIntakeFan);
        if (exhaust <= 0)
            hints.Add(AirflowHint.NoExhaustFan);

        PressureBalance balance = Classify(intake, exhaust);
        if (balance == PressureBalance.Negative)
            hints.Add(AirflowHint.NegativePressure);

        return (new PressureParts(balance, intake, exhaust), hints);
    }

    private static PressureBalance Classify(double intake, double exhaust)
    {
        if (intake <= 0 && exhaust <= 0)
            return PressureBalance.Unknown;
        if (exhaust <= 0)
            return PressureBalance.Positive; // nur Einlass
        if (intake <= 0)
            return PressureBalance.Negative; // nur Auslass

        double ratio = intake / exhaust;
        if (ratio >= BalanceThreshold)
            return PressureBalance.Positive;
        if (ratio <= 1.0 / BalanceThreshold)
            return PressureBalance.Negative;
        return PressureBalance.Balanced;
    }

    // ── Pro-Lüfter-Vorschlag ────────────────────────────────────────────────────

    private static AirflowFanSuggestion BuildSuggestion(FanConfig fan)
    {
        LocationSpec spec = Spec(fan.Location);

        // Netzteil (und jede andere None-Rolle): auf Hardware-Auto lassen, keine Kurve.
        if (spec.Role == AirflowRole.None)
            return Suggestion(fan, spec.Direction, curveId: null, AirflowReason.HardwareAuto);

        // Only the id is needed here, and it is identical across aggressiveness variants.
        RoleCurve curve = CurveFor(spec.Role, AirflowAggressiveness.Balanced);
        AirflowReason reason = fan.Location is FanLocation.Unspecified or FanLocation.Other
            ? AirflowReason.NoPositionDefaultCurve
            : AirflowReason.LocationBasedCurve;

        return Suggestion(fan, spec.Direction, curve.Id, reason);
    }

    private static AirflowFanSuggestion Suggestion(FanConfig fan, AirflowDirection dir, string? curveId, AirflowReason reason) =>
        new()
        {
            FanId = fan.FanId,
            Location = fan.Location,
            Direction = dir,
            SuggestedCurveId = curveId,
            Reason = reason,
        };

    // ── Rolle → Kurvenvorlage ───────────────────────────────────────────────────

    /// <summary>Vorlage einer rollenbasierten Kurve: stabile Id, Anzeigename, Stützpunkte.</summary>
    private sealed record RoleCurve(string Id, string Name, CurvePoint[] Points);

    /// <summary>
    /// Kurvenvorlage je Rolle - Namen neutral englisch (Default; die GUI kann lokalisierte Namen über
    /// <c>curveNames</c> hereinreichen). <see cref="AirflowRole.None"/> hat bewusst keine (wird nie erzeugt).
    /// Id and name are identical across aggressiveness variants; only the point table differs.
    /// </summary>
    private static RoleCurve CurveFor(AirflowRole role, AirflowAggressiveness aggressiveness) => role switch
    {
        AirflowRole.Cpu => new("airflow-cpu", "Airflow · CPU/Radiator", CpuPoints.For(aggressiveness)),
        AirflowRole.Gpu => new("airflow-gpu", "Airflow · GPU", GpuPoints.For(aggressiveness)),
        AirflowRole.Intake => new("airflow-intake", "Airflow · Intake", IntakePoints.For(aggressiveness)),
        AirflowRole.Exhaust => new("airflow-exhaust", "Airflow · Exhaust", ExhaustPoints.For(aggressiveness)),
        AirflowRole.Default => new("airflow-default", "Airflow · Default", DefaultPoints.For(aggressiveness)),
        _ => throw new ArgumentOutOfRangeException(nameof(role), role, "Rolle hat keine Kurvenvorlage (None bekommt keine Kurve)."),
    };

    /// <summary>Point tables of one role in the three aggressiveness variants.</summary>
    private sealed record RolePoints(CurvePoint[] Silent, CurvePoint[] Balanced, CurvePoint[] Performance)
    {
        public CurvePoint[] For(AirflowAggressiveness aggressiveness) => aggressiveness switch
        {
            AirflowAggressiveness.Silent => Silent,
            AirflowAggressiveness.Performance => Performance,
            _ => Balanced,
        };
    }

    // Stützpunkte je Rolle (monoton steigend, enden bei 100 %). Die 100-%-Marke liegt bewusst unter dem
    // FailSafeTempC-Default (90 °C), damit die Kurve volle Drehzahl erreicht, bevor der Watchdog abrupt
    // auf Hardware-Auto zurückfällt: Max-Kurven bei 86 °C; die Avg-Komponenten-Kurven früher (82 °C),
    // weil der Mittelwert dem heißesten Sensor bei Offset-Spreizung (Tctl/Hot-Spot) hinterherläuft.
    // This holds for EVERY aggressiveness variant: silent starts later/lower (0 % like the
    // DefaultProfiles silent curve) but must reach 100 % at the same point; performance gets there
    // much earlier. At every temperature silent ≤ balanced ≤ performance (test-enforced).
    private static readonly RolePoints CpuPoints = new(
        Silent: [new(40, 0), new(55, 15), new(68, 35), new(76, 60), new(82, 100)],
        Balanced: [new(30, 20), new(50, 40), new(65, 65), new(78, 90), new(82, 100)],
        Performance: [new(30, 30), new(45, 55), new(60, 80), new(72, 100)]);

    private static readonly RolePoints GpuPoints = new(
        Silent: [new(40, 0), new(58, 20), new(70, 45), new(78, 70), new(82, 100)],
        Balanced: [new(35, 20), new(55, 45), new(70, 70), new(76, 90), new(82, 100)],
        Performance: [new(30, 30), new(50, 60), new(65, 85), new(75, 100)]);

    private static readonly RolePoints IntakePoints = new(
        Silent: [new(35, 0), new(55, 10), new(68, 30), new(80, 60), new(86, 100)],
        Balanced: [new(30, 15), new(50, 30), new(65, 50), new(80, 80), new(86, 100)],
        Performance: [new(30, 25), new(45, 45), new(60, 70), new(75, 100)]);

    // Auslass liegt bewusst leicht über dem Einlass (zieht Wärme aktiv heraus, hält die Bilanz neutral/positiv).
    private static readonly RolePoints ExhaustPoints = new(
        Silent: [new(35, 0), new(55, 15), new(68, 35), new(80, 65), new(86, 100)],
        Balanced: [new(30, 20), new(50, 38), new(65, 60), new(80, 90), new(86, 100)],
        Performance: [new(30, 30), new(45, 50), new(60, 75), new(75, 100)]);

    private static readonly RolePoints DefaultPoints = new(
        Silent: [new(35, 0), new(55, 10), new(68, 30), new(80, 60), new(86, 100)],
        Balanced: [new(30, 20), new(50, 35), new(65, 55), new(80, 90), new(86, 100)],
        Performance: [new(30, 30), new(45, 50), new(60, 75), new(75, 100)]);

    private static CurveConfig BuildCurve(
        AirflowRole role,
        AirflowAggressiveness aggressiveness,
        SensorSources sensors,
        IReadOnlyDictionary<string, string>? curveNames)
    {
        RoleCurve curve = CurveFor(role, aggressiveness);
        return new CurveConfig
        {
            Id = curve.Id,
            Name = curveNames is not null && curveNames.TryGetValue(curve.Id, out string? name) ? name : curve.Name,
            SourceSensorIds = sensors.For(role),
            // Komponenten-Kurven mitteln ihre eigenen Sensoren (Offset-Sensoren wie Tctl/Hot-Spot
            // überzeichnen sonst); Gehäuse-Kurven folgen der heißesten relevanten Quelle.
            Aggregation = role is AirflowRole.Cpu or AirflowRole.Gpu ? SensorAggregation.Avg : SensorAggregation.Max,
            InterpolationMode = InterpolationMode.Linear,
            HysteresisC = 2.0,
            Points = curve.Points,
        };
    }

    // ── Sensor-Heuristik ────────────────────────────────────────────────────────

    private static readonly string[] CpuKeywords =
        ["cpu", "package", "tctl", "tdie", "coretemp", "k10temp", "core"];

    private static readonly string[] GpuKeywords =
        ["gpu", "amdgpu", "radeon", "nvidia", "geforce", "edge", "junction"];

    private static SensorSources ResolveSensors(IReadOnlyList<SensorConfig> sensors, List<AirflowHint> hints)
    {
        // GPU zuerst und von den CPU-Kandidaten abziehen: GPU-Sensoren heißen oft selbst „… GPU Core"
        // und würden sonst über das CPU-Schlüsselwort „core" mit einsortiert.
        IReadOnlyList<string> gpu = FindSensors(sensors, GpuKeywords);
        var gpuIds = gpu.ToHashSet(StringComparer.Ordinal);
        IReadOnlyList<string> cpu = FindSensors(sensors, CpuKeywords).Where(id => !gpuIds.Contains(id)).ToList();

        string? primary = cpu.Count > 0 ? cpu[0] : gpu.Count > 0 ? gpu[0] : sensors.FirstOrDefault()?.SensorId;

        if (sensors.Count > 0 && cpu.Count == 0)
            hints.Add(AirflowHint.NoCpuSensorDetected);

        return new SensorSources(cpu, gpu, primary);
    }

    /// <summary>Alle Sensoren, deren Name <i>oder</i> Gruppe eines der Schlüsselwörter enthält.</summary>
    private static IReadOnlyList<string> FindSensors(IReadOnlyList<SensorConfig> sensors, string[] keywords) =>
        sensors
            .Where(s => keywords.Any(k =>
                s.Name.Contains(k, StringComparison.OrdinalIgnoreCase)
                || s.Group?.Contains(k, StringComparison.OrdinalIgnoreCase) == true))
            .Select(s => s.SensorId)
            .ToList();

    /// <summary>Aufgelöste Quell-Sensoren (per Namens-/Gruppen-Heuristik) und die Quellenliste je Rolle.</summary>
    private readonly record struct SensorSources(IReadOnlyList<string> Cpu, IReadOnlyList<string> Gpu, string? Primary)
    {
        public IReadOnlyList<string> For(AirflowRole role) => role switch
        {
            AirflowRole.Cpu => Cpu.Count > 0 ? Cpu : Fallback(),
            AirflowRole.Gpu => Gpu.Count > 0 ? Gpu : Fallback(),
            _ => CaseSources(), // Intake/Exhaust/Default → heißeste relevante Quellen, Max-Aggregation
        };

        private IReadOnlyList<string> CaseSources()
        {
            var combined = Cpu.Concat(Gpu).ToList();
            return combined.Count > 0 ? combined : Fallback();
        }

        private IReadOnlyList<string> Fallback() => Primary is not null ? [Primary] : [];
    }

    // ── Merge-Helfer (für Apply) ────────────────────────────────────────────────

    private static IReadOnlyList<CurveConfig> MergeCurves(IReadOnlyList<CurveConfig> existing, IReadOnlyList<CurveConfig> incoming)
    {
        var byId = incoming.ToDictionary(c => c.Id);
        var merged = existing.Select(c => byId.TryGetValue(c.Id, out CurveConfig? replacement) ? replacement : c).ToList();

        var existingIds = existing.Select(c => c.Id).ToHashSet(StringComparer.Ordinal);
        merged.AddRange(incoming.Where(c => !existingIds.Contains(c.Id)));
        return merged;
    }

    private static IReadOnlyList<ProfileAssignment> UpsertAssignments(
        IReadOnlyList<ProfileAssignment> existing,
        IReadOnlyList<AirflowFanSuggestion> suggestions)
    {
        var map = suggestions.ToDictionary(s => s.FanId, s => s.SuggestedCurveId);
        var merged = existing
            .Select(a => map.TryGetValue(a.FanId, out string? curveId) ? a with { CurveId = curveId } : a)
            .ToList();

        var existingFans = existing.Select(a => a.FanId).ToHashSet(StringComparer.Ordinal);
        merged.AddRange(suggestions
            .Where(s => !existingFans.Contains(s.FanId))
            .Select(s => new ProfileAssignment(s.FanId, s.SuggestedCurveId)));
        return merged;
    }
}
