#!/usr/bin/env bash
#
# Installs LinFan as a system service (daemon, root) + GUI launcher.
# Call without sudo — the script publishes as you and only elevates the necessary steps with sudo:
#
#   ./packaging/install.sh
#
# Prerequisites: .NET SDK (apt, NOT snap — snap breaks the GUI/Skia) and systemd.
# ThinkPad: load thinkpad_acpi with fan_control=1, otherwise the daemon cannot write PWM (see README).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX=/opt/linfan
CONFIG_DIR=/etc/linfan
UNIT=linfan-daemon.service

# Release tarball (self-contained bin/, no src/): install from the binaries — no .NET SDK needed.
# A source checkout has src/ but no bin/, so it falls through to the build-from-source path below.
if [ -d "$REPO/bin" ] && [ ! -d "$REPO/src" ]; then
  echo "==> self-contained binaries detected — installing without building (no SDK needed)"
  exec bash "$REPO/packaging/linux/install-bin.sh"
fi

DOTNET="$(command -v dotnet || true)"
[ -n "$DOTNET" ] || { echo "ERROR: 'dotnet' not found in PATH." >&2; exit 1; }
echo "==> dotnet: $DOTNET"

BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT

echo "==> Publish Daemon + GUI (Release)"
dotnet publish -c Release "$REPO/src/LinFan.Daemon" -o "$BUILD/daemon"
dotnet publish -c Release "$REPO/src/LinFan.App"    -o "$BUILD/gui"

# Stop a running service first: overwriting an in-use assembly in $PREFIX would corrupt the loaded
# image of the old daemon (BadImageFormatException). The stop ramps the fans cleanly back to hardware
# auto; the restart below loads the new build.
echo "==> stop a possibly running service (safe upgrade path)"
sudo systemctl stop "$UNIT" 2>/dev/null || true

# Same hazard for the GUI: it memory-maps its assemblies from $PREFIX/gui, so replacing them under
# a running instance makes it segfault mid-flight (apport dialog). Close it, relaunch after the
# install. The pattern only matches processes running from $PREFIX — a dev GUI from a source tree
# is left alone.
GUI_MATCH="$PREFIX/[^ ]*LinFan\.App"
GUI_WAS_RUNNING=
if pgrep -f "$GUI_MATCH" >/dev/null; then
  GUI_WAS_RUNNING=1
  echo "==> close the running GUI (restarted after the install)"
  pkill -f "$GUI_MATCH" || true
  for _ in $(seq 1 25); do pgrep -f "$GUI_MATCH" >/dev/null || break; sleep 0.2; done
  pgrep -f "$GUI_MATCH" >/dev/null && pkill -9 -f "$GUI_MATCH" || true
fi

echo "==> files to $PREFIX (sudo)"
sudo install -d "$PREFIX" "$PREFIX/gui"
# --remove-destination unlinks each target before writing (dpkg-style): a plain cp truncates the
# old inode in place and corrupts the mapped image of anything still running from it.
sudo cp -rT --remove-destination "$BUILD/daemon" "$PREFIX"
sudo cp -rT --remove-destination "$BUILD/gui"    "$PREFIX/gui"

echo "==> GUI launcher $PREFIX/linfan-gui (pins $DOTNET)"
sudo tee "$PREFIX/linfan-gui" >/dev/null <<EOF
#!/usr/bin/env bash
# Generated by install.sh: pin the dotnet runtime so no snap dotnet breaks the GUI.
exec "$DOTNET" "$PREFIX/gui/LinFan.App.dll" "\$@"
EOF
sudo chmod +x "$PREFIX/linfan-gui"
sudo ln -sf "$PREFIX/linfan-gui" /usr/local/bin/linfan   # terminal command: just 'linfan'

echo "==> systemd unit + app-menu entry"
sudo cp "$REPO/packaging/$UNIT"        /etc/systemd/system/
sudo cp "$REPO/packaging/linfan.desktop" /usr/share/applications/
# App icon for the launcher (Icon=linfan in the .desktop). Scalable, so every panel size is covered.
sudo install -D -m0644 "$REPO/src/LinFan.App/Assets/linfan-icon.svg" \
  /usr/share/icons/hicolor/scalable/apps/linfan.svg
# Refresh the desktop caches, otherwise some environments keep showing the previous icon until re-login.
# Best-effort: the tools are missing on minimal systems, and a stale cache is cosmetic.
sudo gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true
sudo update-desktop-database /usr/share/applications 2>/dev/null || true
sudo systemctl daemon-reload

echo "==> configuration ($CONFIG_DIR)"
sudo install -d "$CONFIG_DIR"
if ! sudo test -f "$CONFIG_DIR/config.json"; then
  for src in /root/.config/linfan/config.json "$HOME/.config/linfan/config.json"; do
    if sudo test -f "$src"; then
      echo "    adopting existing configuration: $src"
      sudo cp "$src" "$CONFIG_DIR/config.json"
      break
    fi
  done
fi

echo "==> IPC access group 'linfan' (restricts the daemon socket to its members, not every local account)"
RUN_USER="${SUDO_USER:-$(id -un)}"
sudo groupadd -f --system linfan
NEED_RELOGIN=
if [ "$RUN_USER" != "root" ] && ! id -nG "$RUN_USER" | tr ' ' '\n' | grep -qx linfan; then
  echo "    adding $RUN_USER to group 'linfan'"
  sudo usermod -aG linfan "$RUN_USER"
  NEED_RELOGIN=1
fi

echo "==> enable & (re)start service"
sudo systemctl enable "$UNIT"
sudo systemctl restart "$UNIT"   # restart instead of --now: also loads the new build on upgrade
sleep 1
sudo systemctl --no-pager --full status "$UNIT" || true

if [ -n "$GUI_WAS_RUNNING" ]; then
  if [ "$(id -u)" -eq 0 ]; then
    echo "NOTE: the GUI was closed for the upgrade — start it again via 'linfan' or the app menu."
  else
    echo "==> restart the GUI"
    setsid "$PREFIX/linfan-gui" >/dev/null 2>&1 </dev/null &
  fi
fi

cat <<EOF

Done.
  GUI:     'linfan' in the terminal, or 'LinFan' in the app menu
  Logs:    journalctl -u $UNIT -f
  Config:  $CONFIG_DIR/config.json   (daemon is the sole writer; the GUI saves via IPC)
  Stop:    sudo systemctl stop $UNIT

ThinkPad note: without 'thinkpad_acpi fan_control=1' the daemon runs read-only (no PWM write).
EOF

if [ -n "$NEED_RELOGIN" ]; then
  cat <<EOF
NOTE: $RUN_USER was added to the 'linfan' group — log out and back in (or run 'newgrp linfan')
      for the GUI to reach the daemon socket.
EOF
fi
